#!/bin/bash

if [[ $1 = "-c" ]]; then

    jq '."channel" = ''"'"$2"'"' $HOME/.discho/config.json > /tmp/temp.json && cat /tmp/temp.json > $HOME/.discho/config.json

    echo $(</dev/stdin) > /tmp/discho
    node $HOME/.discho/discho.js 

elif [[ $1 = "-u" ]]; then

	[ ! -t 0 ] && echo $(</dev/stdin) > /tmp/discho || > /tmp/discho

	if [[ $3 = "-c" ]]; then
	    jq '."channel" = ''"'"$4"'"' $HOME/.discho/config.json > /tmp/temp.json && cat /tmp/temp.json > $HOME/.discho/config.json
 	fi
    echo $2 > /tmp/dischofn
    cp $2 $HOME/.discho/out/
    node $HOME/.discho/dischofs.js && rm $HOME/.discho/out/*

elif [[ $1 = "-cb" ]]; then

	[ ! -t 0 ] && echo $(</dev/stdin) > /tmp/discho || > /tmp/discho

	if [[ $3 = "-c" ]]; then
	    jq '."channel" = ''"'"$4"'"' $HOME/.discho/config.json > /tmp/temp.json && cat /tmp/temp.json > $HOME/.discho/config.json
 	fi
    echo $2 > /tmp/dischofn
    cp $2 $HOME/.discho/out/
    node $HOME/.discho/dischofs.js cb && rm $HOME/.discho/out/*

elif [[ $1 = "-t" ]]; then
    
    jq '."token" = ''"'"$2"'"' $HOME/.discho/config.json > /tmp/temp.json && cat /tmp/temp.json > $HOME/.discho/config.json
    echo "Token set to ""$2""!"

elif [[ $1 = "-h" ]]; then
    
    echo "Discho by Elisha Shaddock"
    echo "discho -c <channel-name> to send to a specific channel. defaults to 'general', and stays on the last one you sent to"
    echo "discho -t <TOKEN> sets bot token for the bot"
    echo "discho -u <FILEPATH> will upload this file as an attachement. Append -c <channel-name> to specify a channel, otherwise it will send to the last used"
    echo "discho -cb <FILEPATH> will upload this file as an attatchement, and attempt to post its content as a code block using its file extension as the syntax"
    echo "discho -h shows this"
    echo "discho install: installs this script to /usr/bin/ for systemwide use"
	 
elif [ $? != 0 ]; then

    echo $(</dev/stdin) > /tmp/discho
    node $HOME/.discho/discho.js

elif [ $1 = "install" ]; then

    sudo cp $HOME/.discho/discho /usr/bin/
    echo "Installed to /usr/bin/"

fi
